general:
  path: /home/jiesamb/Env/vapoursynth
  retry_time: 5
  verbose: true

packages:
  - name: python
    repo: https://www.python.org/ftp/python/3.11.1/Python-3.11.1.tar.xz
    version: 3.11.1
    env:
      CFLAGS: -ffat-lto-objects
    run:
      - tar -xf Python-3.11.1.tar.xz
      - cd Python-3.11.1
      - mkdir build
      - cd build
      - ../configure --enable-shared --prefix=/home/jiesamb/Env/vapoursynth
      - make
      - make install

  - name: cython
    version: 0.29.36
    run:
      - pip3 install cython==0.29.36

  - name: meson
    version: 1.3.2
    run:
      - pip3 install meson==1.3.2

  - name: ffmpeg
    repo: https://github.com/AkarinVS/FFmpeg.git
    version: lsmas
    version_is_branch: true
    run:
      - mkdir build
      - cd build
      - ../configure --disable-debug --disable-doc --disable-static --disable-stripping --enable-libdav1d --enable-shared --enable-version3 --prefix=/home/jiesamb/Env/vapoursynth
      - make
      - make install

  - name: zimg
    repo: https://github.com/sekrit-twc/zimg.git
    version: release-3.0.5
    run:
      - ./autogen.sh
      - mkdir build
      - cd build
      - ../configure --prefix=/home/jiesamb/Env/vapoursynth
      - make
      - make install

  - name: vapoursynth-classic
    repo: https://github.com/AmusementClub/vapoursynth-classic.git
    version: R57.A8
    run:
      - ./autogen.sh
      - ./configure --prefix=/home/jiesamb/Env/vapoursynth
      - make -j2
      - make install
      - python3 setup.py sdist -d sdist
      - mkdir empty
      - cd empty
      - pip3 install vapoursynth --no-index --find-links ../sdist
      - cd ../
      - python3 -m unittest discover -s test -p "*test.py"

  - name: lsmash
    repo: https://github.com/l-smash/l-smash.git
    run:
      - mv configure configure.old
      - sed 's/-Wl,--version-script,liblsmash.ver//g' configure.old >configure
      - chmod +x configure
      - mkdir build
      - cd build
      - ../configure --disable-static --prefix=/home/jiesamb/Env/vapoursynth
      - make lib -j2
      - make install-lib -j2

  - name: lsmas
    provide: libvslsmashsource.so
    repo: https://github.com/AkarinVS/L-SMASH-Works.git
    version: vA.3j
    run:
      - cd VapourSynth
      - meson setup ../build
      - ninja -C ../build

  - name: akarin
    provide: libakarin.so
    repo: https://github.com/AkarinVS/vapoursynth-plugin.git
    branch: 0.96
    dependencies:
      - llvm15
      - llvm15-libs
    env:
      LLVM_CONFIG: /usr/bin/llvm-config-15
    run:
      - meson setup build --buildtype=release -Dstatic-llvm=false
      - ninja -C build

  - name: vspreview
    repo: https://github.com/AkarinVS/vapoursynth-preview.git
    version: R57.A4
    run:
      - pip3 install -r requirements.txt
      - cp -r vspreview /home/jiesamb/Env/vapoursynth/lib/python3.11/site-packages/vspreview

  - name: fmtc
    provide: libfmtconv.so
    repo: https://gitlab.com/EleonoreMizo/fmtconv.git
    run:
      - cd build/unix
      - ./autogen.sh
      - ./configure
      - make

  - name: hist
    provide: libhistogram.so
    repo: https://github.com/AmusementClub/vapoursynth-histogram.git
    version: v2.1-AC

  - name: nnedi3
    dependencies: yasm
    provide: libnnedi3.so
    repo: https://github.com/dubhater/vapoursynth-nnedi3.git
    version: v12

  - name: znedi3
    skip: true
    provide: vsznedi3.so,nnedi3_weights.bin
    repo: https://github.com/sekrit-twc/znedi3.git
    run:
      - make X86=1 X86_AVX512=1

  # - name: assrender
  #   provide: libassrender.so
  #   repo: https://github.com/AmusementClub/assrender.git
  #   version: 0.38.1

  - name: bilateral
    provide: libbilateral.so
    repo: https://github.com/AmusementClub/VapourSynth-Bilateral.git
    version: r3.AC

  - name: grain
    provide: libaddgrain.so
    repo: https://github.com/AmusementClub/VapourSynth-AddGrain.git
    version: r10.AC

  - name: dfttest
    provide: libdfttest.so
    repo: https://github.com/AmusementClub/VapourSynth-DFTTest.git
    version: r7.AC

  - name: nlm-ispc
    dependencies: ispc
    provide: libvsnlm_ispc.so
    repo: https://github.com/AmusementClub/vs-nlm-ispc.git
    version: v2
    run:
      - cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_ISPC_INSTRUCTION_SETS="sse2-i32x4;avx1-i32x4;avx2-i32x8" -D CMAKE_ISPC_FLAGS="--opt=fast-math"
      - cmake --build build

  - name: nlm-cuda
    provide: libvsnlm_cuda.so
    repo: https://github.com/AmusementClub/vs-nlm-cuda.git
    version: v1
    run:
      - cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_CUDA_FLAGS="--use_fast_math" -D CMAKE_CUDA_ARCHITECTURES="50;61-real;70-virtual;75-real;86-real;89-real"
      - cmake --build build

  - name: neo_f3kdb
    dependencies: tbb
    provide: libneo-f3kdb.so
    repo: https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb.git
    version: r9
    run:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - cmake --build build

  - name: eedi3m
    dependencies: boost, opencl-headers
    provide: libeedi3m.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3.git
    version: r4

  - name: sangnom
    provide: libsangnom.so
    repo: https://github.com/dubhater/vapoursynth-sangnom.git
    version: r42

  - name: eedi2
    provide: libeedi2.so
    repo: https://github.com/AmusementClub/VapourSynth-EEDI2.git
    version: r7.1-AC

  - name: tivtc
    provide: libtivtc.so
    repo: https://github.com/dubhater/vapoursynth-tivtc.git
    version: v2

  - name: adaptivebinarize
    provide: libadaptivebinarize.so
    repo: https://github.com/AmusementClub/vapoursynth-adaptivebinarize.git
    version: r1.AC

  - name: autocrop
    provide: libautocrop.so
    repo: https://github.com/AmusementClub/vapoursynth-autocrop.git
    version: 0.1-AC

  - name: bm3d
    provide: libbm3d.so
    repo: https://github.com/AmusementClub/VapourSynth-BM3D.git
    version: r9.AC

  - name: bm3dcuda
    provide: libbm3dcuda.so,libbm3dcuda_rtc.so,libbm3dcpu.so
    repo: https://github.com/WolframRhodium/VapourSynth-BM3DCUDA.git
    version: R2.14
    run:
      - cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math -Wno-deprecated-gpu-targets" -D CMAKE_CUDA_ARCHITECTURES="50;61-real;75-real;86" -DVAPOURSYNTH_INCLUDE_DIRECTORY="/home/jiesamb/Env/vapoursynth/include/vapoursynth"
      - cmake --build build --config Release

  - name: boxblur
    provide: libboxblur.so
    repo: https://github.com/AmusementClub/vs-boxblur.git
    version: v3

  - name: bwdif
    provide: libbwdif.so
    repo: https://github.com/AmusementClub/VapourSynth-Bwdif.git
    version: r4.1-AC

  - name: cas
    provide: libcas.so
    repo: https://github.com/AmusementClub/VapourSynth-CAS.git
    version: r2.AC

  - name: chickendream
    provide: libchickendream.so
    repo: https://gitlab.com/EleonoreMizo/chickendream.git
    version: r2
    run:
      - cd build/unix
      - chmod +x autogen.sh
      - ./autogen.sh
      - ./configure
      - make

  - name: CTMF
    provide: libctmf.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-CTMF.git
    version: r5

  - name: dv2source
    provide: libd2vsource.so
    repo: https://github.com/dwbuiten/d2vsource.git

  - name: dctfilter
    provide: libdctfilter.so
    repo: https://github.com/AmusementClub/VapourSynth-DCTFilter.git
    version: r3.1A

  - name: Deblock
    provide: libdeblock.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Deblock.git

  - name: DeblockPP7
    provide: libdeblockpp7.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-DeblockPP7.git

  - name: Delogo
    provide: libDelogoHD.so
    repo: https://github.com/HomeOfAviSynthPlusEvolution/DelogoHD.git
    version: r12

  - name: descale
    provide: libdescale.so
    repo: https://github.com/Irrational-Encoding-Wizardry/descale.git

#   # 另有cuda选项
  - name: dfttest2
    provide: libdfttest2_cpu.so,libdfttest2_cuda.so,libdfttest2_nvrtc.so
    repo: https://github.com/AmusementClub/vs-dfttest2.git
    submodule: true
    flag: -D ENABLE_CPU=ON -D ENABLE_CUDA=OFF
    run:
      - cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_FLAGS_RELEASE="-ffast-math -march=native" -D ENABLE_CUDA=1 -D USE_NVRTC_STATIC=ON -D ENABLE_CPU=1
      - cmake --build build


  - name: DotKill
    provide: libdotkill.so
    repo: https://github.com/myrsloik/DotKill.git
    run:
      - |
          echo "all:
          	  g++ -c -std=gnu++17 -fPIC   -I. -I/home/jiesamb/Env/vapoursynth/include/vapoursynth -o dotkill1.o dotkill1.cpp
          	  g++ -shared -fPIC  -o libdotkill.so dotkill1.o" > Makefile
      - make

  - name: dpid
    provide: libdpid.so
    repo: https://github.com/WolframRhodium/VapourSynth-dpid.git
    version: r6
    run:
      - cd Source
      - meson setup build
      - ninja -C build

  - name: Edgefixer
    provide: libvsedgefixer.so
    repo: https://github.com/sekrit-twc/EdgeFixer.git
    version: r2
    run:
      - |
          echo "all:
          	  gcc -c -fPIC   -I./EdgeFixer -I/home/jiesamb/Env/vapoursynth/include/vapoursynth -o vsplugin.o EdgeFixer/vsplugin.c
          	  gcc -c -fPIC   -I./EdgeFixer -I/home/jiesamb/Env/vapoursynth/include/vapoursynth -o edgefixer.o EdgeFixer/edgefixer.c

          	  gcc -shared -fPIC  -o libvsedgefixer.so vsplugin.o edgefixer.o" > Makefile
      - make

  - name: fft3dfilter
    provide: libfft3dfilter.so
    repo: https://github.com/AmusementClub/VapourSynth-FFT3DFilter.git

  - name: fftspectrum
    provide: libfftspectrum.so
    repo: https://github.com/Beatrice-Raws/FFTSpectrum.git
    env:
      CFLAGS: -march=native

  - name: fillborder
    provide: libfillborders.so
    repo: https://github.com/AmusementClub/vapoursynth-fillborders.git
    version: v2.1-AC

  - name: frfun7
    provide: libfrfun7.so
    repo: https://github.com/AmusementClub/vapoursynth-frfun7.git
    version: v2.AC

  - name: ils
    provide: libils.so
    repo: https://github.com/AmusementClub/VapourSynth-ILS.git
    version: v2
    run:
      - cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math -Wno-deprecated-gpu-targets" -D CMAKE_CUDA_ARCHITECTURES="50;61-real;75-real;86" -DVAPOURSYNTH_INCLUDE_DIRECTORY="/home/jiesamb/Env/vapoursynth/include/vapoursynth"
      - cmake --build build --config Release

  - name: knlmeanscl
    provide: libknlmeanscl.so
    repo: https://github.com/AmusementClub/KNLMeansCL.git
    version: v1.1.1e-AC

  - name: awarpsharp2
    provide: libawarpsharp2.so
    repo: https://github.com/dubhater/vapoursynth-awarpsharp2.git
    version: v4

  - name: bifrost
    provide: libbifrost.so
    repo: https://github.com/dubhater/vapoursynth-bifrost.git

  - name: cnr2
    provide: libcnr2.so
    repo: https://github.com/dubhater/vapoursynth-cnr2.git

  - name: decross
    provide: libdecross.so
    repo: https://github.com/dubhater/vapoursynth-decross.git

  - name: degrainmedian
    provide: libdegrainmedian.so
    repo: https://github.com/dubhater/vapoursynth-degrainmedian.git

  - name: fieldhint
    provide: libfieldhint.so
    repo: https://github.com/dubhater/vapoursynth-fieldhint.git

  - name: fluxsmooth
    provide: libfluxsmooth.so
    repo: https://github.com/dubhater/vapoursynth-fluxsmooth.git

  - name: hqdn3d
    provide: libhqdn3d.so
    repo: https://github.com/Hinterwaeldlers/vapoursynth-hqdn3d.git

  - name: minideen
    provide: libminideen.so
    repo: https://github.com/dubhater/vapoursynth-minideen.git
    version: v2

  - name: motionmask
    provide: libmotionmask.so
    repo: https://github.com/dubhater/vapoursynth-motionmask.git

  - name: msmoosh
    provide: libmsmoosh.so
    repo: https://github.com/dubhater/vapoursynth-msmoosh.git
    version: v1.1

  - name: tcanny
    provide: libtcanny.so
    repo: https://github.com/AmusementClub/VapourSynth-TCanny.git
    version: r14.AC4
    env:
      CC: clang
      CXX: clang++

  - name: retinex
    provide: libretinex.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Retinex.git

  - name: mvtools
    dependencies: nasm,fftw
    provide: libmvtools.so
    repo: https://github.com/AmusementClub/vapoursynth-mvtools.git
    version: v23.1-AC

  - name: scxvid
    provide: libscxvid.so
    repo: https://github.com/dubhater/vapoursynth-scxvid.git

  - name: smoothuv
    provide: libsmoothuv.so
    repo: https://github.com/dubhater/vapoursynth-smoothuv.git
    version: v3
    env:
      CXXFLAGS: "-march=x86-64 -fpeel-loops"

  - name: tcomb
    provide: libtcomb.so
    repo: https://github.com/dubhater/vapoursynth-tcomb.git
    version: v4

  - name: temporalsoften2
    provide: libtemporalsoften2.so
    repo: https://github.com/dubhater/vapoursynth-temporalsoften2.git

  - name: videoscope
    provide: libvideoscope.so
    repo: https://github.com/dubhater/vapoursynth-videoscope.git

  - name: wwxd
    provide: libwwxd.so
    repo: https://github.com/dubhater/vapoursynth-wwxd.git
    run:
      - |
        echo "all:
        	  gcc -c -fPIC -Wall -Wextra -Wno-unused-parameter   -I. -I/home/jiesamb/Env/vapoursynth/include/vapoursynth -o wwxd.o src/wwxd.c
        	  gcc -c -fPIC -Wall -Wextra -Wno-unused-parameter   -I. -I/home/jiesamb/Env/vapoursynth/include/vapoursynth -o detection.o src/detection.c
        	  gcc -shared -fPIC  -o libwwxd.so wwxd.o detection.o" > Makefile
      - make

  - name: mpls
    provide: libreadmpls.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-ReadMpls.git
    version: r5

  - name: remapframes
    provide: libremapframes.so
    repo: https://github.com/Irrational-Encoding-Wizardry/Vapoursynth-RemapFrames.git
    version: v1.1

  - name: tdeintmod
    provide: libtdeintmod.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TDeintMod.git

  - name: templinearapproximate
    provide: libtemplinearapproximate.so
    repo: https://bitbucket.org/mystery_keeper/templinearapproximate-vapoursynth.git
    run:
      - |
        echo "all:
        	  gcc -c -fPIC   -I. -I/home/jiesamb/Env/vapoursynth/include/vapoursynth -o main.o src/main.c
        	  gcc -c -fPIC   -I. -I/home/jiesamb/Env/vapoursynth/include/vapoursynth -o processplane.o src/processplane.c
        	  gcc -shared -fPIC  -o libtemplinearapproximate.so main.o processplane.o" > Makefile
      - make

  - name: tnlmeans
    provide: libtnlmeans.so
    repo: https://github.com/AmusementClub/VapourSynth-TNLMeans.git
    version: v1.AC

  - name: tonemap
    provide: libtonemap.so
    repo: https://github.com/ifb/vapoursynth-tonemap.git
    version: R2

  - name: ttempsmooth
    provide: libttempsmooth.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TTempSmooth.git
    version: r4.1

  - name: vcm
    provide: libvcmod.so
    repo: https://github.com/AmusementClub/vcm.git

  - name: vfrtocfr
    provide: libvfrtocfr.so
    repo: https://github.com/AmusementClub/Vapoursynth-VFRToCFR.git

  - name: delogo
    provide: libdelogo.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-DeLogo.git
    version: v0.4
    run:
      - ./configure
      - make

  - name: yadifmod
    provide: libyadifmod.so
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Yadifmod.git

  - name: vsmlrt-trt
    provide: libvstrt.so
    repo: https://github.com/AmusementClub/vs-mlrt.git
    dependencies: tensort
    run:
      - ln -s /usr/bin/trtexec /home/jiesamb/Env/vapoursynth/plugins/vsmlrt-cuda/trtexec
      - cd vstrt
      - cmake -S . -B build -G Ninja -LA -D CMAKE_BUILD_TYPE=Release -D VAPOURSYNTH_INCLUDE_DIRECTORY="/home/jiesamb/Env/vapoursynth/include/vapoursynth" -D CMAKE_CXX_COMPILER=g++-12 -D CMAKE_CXX_FLAGS="-Wall -ffast-math -march=x86-64-v3"
      - cmake --build build


#   # 编译看起来有点复杂，之后搞
#   - name: ffms2
#     skip: true
#     provide:
#     repo: https://github.com/FFMS/ffms2.git
#     version: 2.40
#     flag:

#   # python 3.11 无法编译
#   - name: f3kdb
#     provide: libf3kdb.so
#     repo: https://github.com/AmusementClub/flash3kyuu_deband.git
#     version: 2.0.1-AC
#     make: |
#       ./waf configure
#       ./waf build
#       cd build

  # # come with vapoursynth
  # - name: imwri
  #   skip: true

#   # 自带滤镜
#   - name: resize
#     skip: true

#   # 自带滤镜
#   - name: rgvs
#     skip: true
#     provide: libremovegrain.so
#     repo: https://github.com/vapoursynth/vs-removegrain.git
#     version: R1

#   # 仅有msvc编译文件
#   - name: textsub
#     skip: true
#     provide:
#     repo: https://github.com/HomeOfVapourSynthEvolution/xy-VSFilter.git
#     version: r3

#   # 未找到repo
#   - name: complane
#     skip: true
#     provide:
#     repo:
#     version:

#   # 没有找到任何信息
#   - name: ftf_em64t_avx_fma
#     skip: true
#     provide:
#     repo:
#     version:

# 仓库没了
  # - name: gradcurve
  #   provide: libgradcurve.so
  #   repo: https://github.com/Jieiku/GradCurve.git

#   # 娱乐部的改进版不一样
#   # 需要研究下怎么编译
#   # 只编译了原版
#   - name: vs-placebo
#     provide: libvs_placebo.so
#     repo: https://github.com/Lypheo/vs-placebo.git

#   # 没有找到repo
#   - name: minsrp
#     skip: true
#     provide:
#     repo:
#     version:

#   # 没有找到repo
#   - name: avsreader
#     skip: true

#   - name: vscube
#     skip: true

#   - name: vsfiltermod
#     skip: true

#   - name: vsncnn
#     skip: true

#   - name: nlm_cuda
#     skip: true

#   - name: nlm_ispc
#     skip: true

#   - name: vsort
#     skip: true

#   - name: vsov
#     skip: true


#   - name: vstrt
#     skip: true

  # 仓库无人维护
  # - name: vaguedenoiser
  #   provide: libvaguedenoiser.so
  #   repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-VagueDenoiser.git

  # - name: vsrawsource
  #   provide: libvsrawsource.so
  #   repo: https://github.com/HolyWu/vsrawsource.git
  #   version: 20191105

  # - name: w3fdif
  #   provide: libw3fdif.so
  #   repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-W3FDIF.git

  # - name: wnnm
  #   repo: https://github.com/AmusementClub/VapourSynth-WNNM.git
  #   run:
  #     - cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D MKL_LINK=static -D MKL_THREADING=sequential -D MKL_INTERFACE=lp64
  #     - cmake --build build
